[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma migrate resolve --applied 20260113140026_init; npx prisma migrate resolve --applied 20260113151808_loan_photo_table; npx prisma migrate resolve --applied 20260124100150_init; npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
